import{a as m,S as p,i as y}from"./assets/vendor-CZCqCKWq.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const f="49627235-4d8b848df827aeac6c5905e8e",h="https://pixabay.com/api/";function g(s){return m.get(h,{params:{key:f,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(r=>r.data.hits).catch(r=>(console.error("Error fetching images:",r.message),[]))}const b=new p(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250}),u=document.querySelector(".gallery");document.querySelector(".loader");function v(s){return s.map(({webformatURL:r,largeImageURL:o,tags:l,likes:e,views:t,comments:a,downloads:d})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${o}">
          <img class="gallery-image" src="${r}" alt="${l}" loading="lazy" />
        </a>
        <div class="thumb-block">
          <div class="block"><h2 class="tittle">Likes</h2><p class="amount">${e}</p></div>
          <div class="block"><h2 class="tittle">Views</h2><p class="amount">${t}</p></div>
          <div class="block"><h2 class="tittle">Comments</h2><p class="amount">${a}</p></div>
          <div class="block"><h2 class="tittle">Downloads</h2><p class="amount">${d}</p></div>
        </div>
      </li>`).join("")}function L(s){q(),u.innerHTML=v(s),b.refresh()}function q(){u.innerHTML=""}function i(s){y.error({title:"Error",message:s,position:"topRight"})}const c=document.querySelector(".form"),S=document.querySelector(".input-search"),P=document.querySelector(".gallery"),n=document.querySelector(".loader");n.style.display="none";c.addEventListener("submit",function(s){s.preventDefault();const r=S.value.trim();if(r===""){i("Please enter a search query!");return}P.innerHTML="",n.style.display="block",g(r).then(o=>{if(n.style.display="none",o.length===0){i("Sorry, there are no images matching your search query. Please try again!");return}L(o)}).catch(o=>{n.style.display="none",i("Error fetching images. Please try again!"),console.error("Помилка сервера:",o.message)}),c.reset()});
//# sourceMappingURL=index.js.map
